In [15]:
import numpy as np
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
result_matrix = np.dot(A, B)
print(f"行列の積:\n{result_matrix}")
max_value = result_matrix.max()
print(f"行列の要素の最大値: {max_value}")

行列の積:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
行列の要素の最大値: 47
